name: Demo Python Tests

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  python-tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [jeff-demo-desktop-eu, jeff-demo-mobile-web-vdc-eu, jeff-demo-mobile-web-rdc-eu, jeff-demo-mobile-native-eu-android, jeff-demo-mobile-native-eu-ios]
    steps:
      - uses: saucelabs/sauce-connect-action@v2.1.1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelName: github-action-tunnel
          configFile: ${{ github.workspace }}/sc-configuration/config.yaml
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install
      - name: Run ${{ matrix.test }} tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: pipenv run ${{ matrix.test }}
