name: Cron Job Jeff Demo Python Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "* */6 * * *"

jobs:
  python-tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: [jeff-demo-desktop-eu, jeff-demo-mobile-web-vdc-eu, jeff-demo-mobile-web-rdc-eu, jeff-demo-mobile-native-eu-android, jeff-demo-mobile-native-eu-ios]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: pipenv install
      - name: Run ${{ matrix.test }} tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: pipenv run ${{ matrix.test }}